[theme]
primaryColor = "#FACC15"
backgroundColor = "#0B2239"
secondaryBackgroundColor = "#123A63"
textColor = "#E2E8F0"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "tcc-solar-guiaizza.streamlit.app"
serverPort = 443
iconUrl = "https://raw.githubusercontent.com/guiaizza-dotcom/tcc_solar/main/app/icon.png"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[ui]
hideTopBar = false
hideFooterWatermark = false
